### ISSUE TITLE
Inconsistent font size.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Flym#28] opened 2018-12-26 22:22 UTC
After double-changing the device's orientation font-size enlarges and UI language reverts to _Android default_

**Comment by SIRSteiner** [comment] 2018-12-27 16:53
> UI language reverts to Android default

Same here

> font-size enlarges

I cannot reproduce it

**Comment by yanus171** [comment] 2019-01-02 06:43
In article list windows or in article text window?

**Comment by yanus171** [comment] 2019-01-02 06:46
Cannot reproduce it too

**Comment by ThomasLeigh** [comment] 2019-01-02 16:14
I use bigger font size both in articles and article list. Besides I use an UI language other than Android default.

The issue has to do with font size varying undesirably of both article list and settings (not in single articles).

I've detected it both on Android 6 and 7, two different devices.

**Comment by SIRSteiner** [comment] 2019-01-02 17:51
I think we should split this issue in "Inconsistent font size" and "Inconsistant UI language". Therefore I will open another issue "Inconsistant UI language" with a screenrecord. Please rename this issue. Thank you

**Comment by ThomasLeigh** [comment] 2019-01-02 18:04
Oh, and one more thing: font size is changing also in the sidebar.

**Comment by SIRSteiner** [comment] 2019-01-02 18:10
Can you describe in details with font size settings how we can reproduce this issue? Maybe with screenrecording?

**Comment by ThomasLeigh** [comment] 2019-01-02 18:47
Sure, here You are:
[https://drive.google.com/file/d/16nl_KJkPNrPOzjt6ndc4_eWebBOGlik7/view?usp=sharing](url)

**Comment by ThomasLeigh** [comment] 2019-01-02 18:50
Article list font size: +5
Article text font size: +5

**Comment by SIRSteiner** [comment] 2019-01-02 19:55
Sorry, I did everything but neither on my smartphone nor on my tablets this issue occur.

**Comment by yanus171** [comment] 2019-03-28 03:00
Try this https://github.com/yanus171/Flym/releases/tag/v0.7.50

**Comment by ThomasLeigh** [comment] 2019-03-28 17:40
The issue doesn't occur anymore, thank You :)

**Comment by yanus171** [comment] 2019-03-28 18:31
Was this issue resolved by this version or earlier?

**Comment by ThomasLeigh** [comment] 2019-03-28 19:45
I didn't check it earlier on, just now because of the dedicated fix.

**Closed** 2019-05-10 13:46 UTC
